requires 'OpusVL::AppKit';
requires 'OpusVL::CMS';
requires 'Moose';
requires 'namespace::autoclean';
requires 'Template::Plugin::HTML::Strip';
build_requires 'Catalyst::Runtime' => '5.80015';
build_requires 'Test::WWW::Mechanize::Catalyst';
build_requires 'Test::More' => '0.88';
author_requires 'Test::Pod::Coverage' => '1.04';
author_requires 'Test::Pod' => '1.14';